#!/usr/bin/env bash

echo "use 8 ierne ingits and a restonelamp to kraft a microskop botum"
echo "use sillk redstone and lever to make a microskop botum"
echo "use redstone lamp to make microskop lightbylb"
echo "use 8 inerningets a pese uv glass to make a microskop top"
echo "a microskop top a microskop botum a microskop lightbylb to make a microskop"
echo "hou brite  do you wont your microskop lite plese chose a number between 1 and 10"
read lite
echo "hou much do you want to zoom in on the microskop plese choos a number between 100 and 1 rede"
read zoom
